// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SectionedUITableViewSample {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				return ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
			}
			set {
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("tvc")]
		private MonoTouch.UIKit.UITableViewController tvc {
			get {
				return ((MonoTouch.UIKit.UITableViewController)(this.GetNativeField("tvc")));
			}
			set {
				this.SetNativeField("tvc", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("tv")]
		private MonoTouch.UIKit.UITableView tv {
			get {
				return ((MonoTouch.UIKit.UITableView)(this.GetNativeField("tv")));
			}
			set {
				this.SetNativeField("tv", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("searchBar")]
		private MonoTouch.UIKit.UISearchBar searchBar {
			get {
				return ((MonoTouch.UIKit.UISearchBar)(this.GetNativeField("searchBar")));
			}
			set {
				this.SetNativeField("searchBar", value);
			}
		}
	}
}
